project:
  type: website
  output-dir: .  # Ensure the output goes to the root of 'docs' folder

website:
  title: "Haley Vivian Portfolio"
  navbar:
    right:
      - text: "Home"
        href: "#home"
      - text: "About"
        href: "#about"
      - text: "Portfolio"
        href: "#portfolio"
  search: true  # Enable search functionality